### PR TITLE
Changed beenHere so now lib complies with latest foursquare API.

### PR DESCRIPTION
**Pull request by zilet**

### CODE REVIEW

**Comment by mattupstate** [comment]
I don't see a change in any of the test data that reflects the change in the foursquare API. Any reason for this?

**Comment by zilet** [comment]
UserTemplateTest.java has been updated so it will pass the test.

**Comment by mattupstate** [comment]
The test data (json files) should be updated to reflect the exact output of the foursquare API. A positive integer converts to a true value, I believe so the test would naturally pass.

**Comment by zilet** [comment]
Hmm when I take another look there is a flaw here. I tested in my app
directly with Foursquare but now I identified that beenHere is actually
returned in the form of

beenHere: {
- count: 2
- marked: true

}

Which will require a full BeenHere object. I think that
https://github.com/cemcatik/spring-social-foursquare fix it the right way.

On Mon, Jul 30, 2012 at 7:52 PM, Matt Wright <
reply@reply.github.com

> wrote:
> 
> The test data (json files) should be updated to reflect the exact output
> of the foursquare API. A positive integer converts to a true value, I
> believe so the test would naturally pass.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/mattupstate/spring-social-foursquare/pull/15#issuecomment-7376075

## 

Pozdrav,
Miloš

**Comment by mattupstate** [comment]
Got it. Thanks.

**Pull request closed without merging**
